server:
  port: 3081
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: student
        uri: http://localhost:3001/
        predicates:
        - Path=/students/**
      - id: schoolModule
        uri: http://localhost:3002/
        predicates:
        - Path=/administration/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka
  registerWithEureka:
       - true
  fetchRegistry:
       - true